WIP agrego normalizado y copaido de librerias falta arreglar obtecion de headers

diff --git a/.github/workflows/build-boost-android.yml b/.github/workflows/build-boost-android.yml
--- a/.github/workflows/build-boost-android.yml
+++ b/.github/workflows/build-boost-android.yml
@@ -59,10 +59,36 @@ jobs:
       - name: Verify built libraries
         run: |
           find build -name "libboost*.a"
+      - name: Normalize and copy libs
+        run: |
+          ABIS="arm64-v8a armeabi-v7a x86 x86_64"
 
+          for ABI in $ABIS; do
+            mkdir -p output/libs/$ABI
+
+            find build -path "*/$ABI/*" -name "libboost_*-clang-mt-*.a" -print0 | while IFS= read -r -d '' f; do
+              base=$(basename "$f")
+
+              simple=$(echo "$base" | sed -E 's/(libboost_[^ -]+).*/\1.a/')
+
+              cp "$f" "output/libs/$ABI/$simple"
+            done
+          done
+      - name: Copy headers
+        run: |
+          mkdir -p output/include
+
+          HEADER_PATH=$(find build -type d -path "*/include/boost" | head -n 1)
+
+          if [ -z "$HEADER_PATH" ]; then
+            echo "ERROR: Boost headers not found"
+            exit 1
+          fi
+
+          cp -r "$HEADER_PATH" output/include/
       - name: Package build
         run: |
-          tar -czf boost-${BOOST_VERSION}-ndk-${NDK_VERSION}.tar.gz build
+          tar -czf boost-${BOOST_VERSION}-ndk-${NDK_VERSION}.tar.gz output
       - name: Create Release
         uses: softprops/action-gh-release@v2
         with:
